### PR TITLE
add release page for v2.3.0

### PR DESCRIPTION
**Pull request by willson-chen**

### CODE REVIEW

**Comment by vapier** [comment]
@willson-chen can you redo all of these commits ?  we don't merge to this repo directly.  all commits should be going into https://github.com/libgd/website/ instead, and then the infra takes care of generating & pushing to this repo.

i don't want to commit the announce for the new 2.3.2 release as i'm pretty sure it'll clobber everything you've done in here.

**Comment by vapier** [comment]
@willson-chen ping ... i don't want to clobber all your work in here

**Comment by vapier** [comment]
@pierrejoye could you add me as an admin to https://github.com/libgd/website to help roll this stuff back ?

**Comment by pierrejoye** [comment]
Done (full org). Also should remove the owners team as they are purely roles now in github. I should read carefully the doc before doing it lol.

**Pull request merged**
